general.import = [
    "~/.config/alacritty/themes/themes/miasma_dg.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15

decorations = "Buttonless"

opacity = 0.90
blur = false

option_as_alt = "Both"

[font]
normal = { family = "Monofur Nerd Font Mono", style = "Regular" }
bold = { family = "Monofur Nerd Font Mono", style = "Regular" }

size = 20

[colors.primary]
background = "#222222"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"
